# Generated by Django 6.1 on 2026-08-25 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fabric', 'Fabric'), ('accesories', 'Accesories'), ('zipper', 'Zipper')], max_length=20)),
                ('supplier_code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(choices=[('yds', 'Yds'), ('mtrs', 'Mtrs'), ('pcs', 'Pcs'), ('kgs', 'Kgs')], max_length=20)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier', to='factories.factory')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'ordering': ['id'],
            },
        ),
    ]
