# Generated by Django 6.1 on 2026-08-26 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['description']},
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='factories.factory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('fabric', 'Fabric'), ('trims', 'Trims'), ('accessories', 'Accessories'), ('packaging', 'Packaging'), ('label', 'Label'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pcs'), ('yds', 'Yards'), ('mtr', 'Meter'), ('kg', 'Kg'), ('gm', 'Gram'), ('set', 'Set'), ('dozen', 'Dozen'), ('roll', 'Roll')], default='pcs', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
