# Generated by Django 6.1 on 2026-08-28 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0001_initial'),
        ('items', '0002_alter_item_options_alter_item_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('shorts', 'Shorts'), ('pants', 'Pants'), ('shirt', 'Shirt'), ('t_shirt', 'T-Shirt'), ('polo', 'Polo'), ('jacket', 'Jacket'), ('dress', 'Dress'), ('skirt', 'Skirt'), ('sweater', 'Sweater'), ('outerwear', 'Outerwear'), ('other', 'Other')], max_length=20)),
                ('buyer_style', models.CharField(help_text="Buyer's style number, e.g. WS806G318", max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, help_text='Fabric content / construction, e.g. 100% Polyester T400 75D...', verbose_name='Content')),
                ('finish', models.CharField(blank=True, help_text='Wash/finish code, e.g. NW, GW', max_length=50, verbose_name='Finish')),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Reference FOB unit price', max_digits=10)),
            ],
            options={
                'verbose_name': 'Finished Item',
                'ordering': ['buyer_style'],
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='factories.factory'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FinishedItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44')], max_length=10)),
                ('sku', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('discontinued', 'Discontinued')], default='active', max_length=15)),
                ('finished_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='items.finisheditem')),
            ],
            options={
                'verbose_name': 'Finished Item Variant',
                'ordering': ['finished_item', 'color_name', 'size'],
                'unique_together': {('finished_item', 'color_name', 'size')},
            },
        ),
    ]
