# Generated by Django 6.1 on 2026-08-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_finisheditem_alter_item_supplier_finisheditemvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finisheditemvariant',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10),
        ),
    ]
