# Generated by Django 6.1 on 2026-08-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('factories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True)),
                ('pi_number', models.CharField(blank=True, max_length=30)),
                ('order_type', models.CharField(choices=[('sample', 'Sample'), ('bulk', 'Bulk')], default='bulk', max_length=10)),
                ('sourcing_responsibility', models.CharField(choices=[('buyer', 'Buyer-sourced fabric (CM only)'), ('factory', 'Factory-sourced (fabric+trims)')], default='factory', max_length=10)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('costing', 'Costing'), ('negotiation', 'Price Negotiation'), ('confirmed', 'Confirmed'), ('booking', 'Booking'), ('in_production', 'In Production'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='inquiry', max_length=20)),
                ('style', models.CharField(max_length=50)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('required_ship_date', models.DateField(blank=True, null=True)),
                ('planned_ship_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='buyers.buyer')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='factories.factory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='orders.order')),
            ],
        ),
    ]
