# Generated by Django 6.1 on 2026-09-11 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('factories', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_order_number', models.CharField(blank=True, help_text="Buyer's own PO number, e.g. WC6824", max_length=30)),
                ('order_type', models.CharField(choices=[('sample', 'Sample'), ('bulk', 'Bulk')], default='bulk', max_length=10)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('costing', 'Costing'), ('negotiation', 'Price Negotiation'), ('confirmed', 'Confirmed'), ('booking', 'Booking'), ('in_production', 'In Production'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='inquiry', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('required_ship_date', models.DateField(blank=True, null=True)),
                ('planned_ship_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='buyers.buyer')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='factories.factory')),
                ('ship_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='buyers.buyershipto', verbose_name='Ship To')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pack', models.CharField(default='A', help_text='Pack code, e.g. A/B/C', max_length=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='items.finisheditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='orders.orderitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_breakdown_lines', to='items.finisheditemvariant')),
            ],
            options={
                'verbose_name': 'Order Item Breakdown',
                'verbose_name_plural': 'Order Item Breakdowns',
                'ordering': ['id'],
            },
        ),
    ]
