# Generated by Django 6.1 on 2026-08-28 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_buyershipto'),
        ('factories', '0001_initial'),
        ('items', '0003_finisheditem_alter_item_supplier_finisheditemvariant'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pi_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sourcing_responsibility',
        ),
        migrations.RemoveField(
            model_name='order',
            name='style',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_order_number',
            field=models.CharField(blank=True, help_text="Buyer's own PO number, e.g. WC6824", max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='our_order_number',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='buyers.buyershipto', verbose_name='Ship To'),
        ),
        migrations.AddField(
            model_name='order',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='factories.factory'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pack', models.CharField(default='A', help_text='Pack code, e.g. A/B/C', max_length=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='items.finisheditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='orders.orderitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_breakdown_lines', to='items.finisheditemvariant')),
            ],
            options={
                'verbose_name': 'Order Item Breakdown',
                'verbose_name_plural': 'Order Item Breakdowns',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='OrderBreakdown',
        ),
    ]
