# Generated by Django 6.1 on 2026-08-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_order_number_remove_order_pi_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='our_order_number',
        ),
    ]
