# Generated by Django 6.1 on 2026-08-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_sequence', models.PositiveSmallIntegerField()),
                ('planned_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['split_sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProductionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('cutting', 'Cutting'), ('sewing', 'Sewing'), ('finishing', 'Finishing'), ('packing', 'Packing')], max_length=15)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('quantity_completed', models.PositiveIntegerField(default=0)),
                ('lc_status', models.CharField(blank=True, max_length=50)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('ready_quantity', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_updates', to='orders.order')),
            ],
            options={
                'ordering': ['-update_date'],
            },
        ),
    ]
