# Generated by Django 6.1 on 2026-08-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factories', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=30, unique=True)),
                ('material_type', models.CharField(choices=[('fabric', 'Fabric'), ('trims', 'Trims'), ('accessories', 'Accessories')], max_length=15)),
                ('booking_date', models.DateField()),
                ('expected_receiving_date', models.DateField(blank=True, null=True)),
                ('actual_receiving_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('partial', 'Partially Received'), ('received', 'Fully Received')], default='booked', max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_pos', to='orders.order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_pos', to='factories.factory')),
            ],
            options={
                'verbose_name': 'Supplier PO',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('supplier_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.supplierpo')),
            ],
        ),
    ]
