# Generated by Django 6.1 on 2026-08-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('factories', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('due_date', models.DateField()),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Received'), ('received', 'Received')], default='pending', max_length=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='buyers.buyer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='orders.order')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('approval_status', models.CharField(default='pending', max_length=15)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='buyers.buyer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='orders.order')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('received', 'Money Received'), ('paid', 'Money Paid'), ('bank_transfer', 'Bank Transaction')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='completed', max_length=15)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='buyers.buyer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='factories.factory')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProfitabilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('claim_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contribution', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contribution_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profitability', to='orders.order')),
            ],
        ),
    ]
