# Generated by Django 6.1 on 2026-08-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('factory_type', models.CharField(choices=[('garment', 'Garment Factory'), ('material_supplier', 'Material Supplier')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Factories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FactoryCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100)),
                ('monthly_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='factories.factory')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryCommercialTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('moq', models.PositiveIntegerField(blank=True, null=True)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('price_terms', models.CharField(blank=True, max_length=50)),
                ('shipment_terms', models.CharField(blank=True, max_length=50)),
                ('factory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_terms', to='factories.factory')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=100)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='factories.factory')),
            ],
            options={
                'verbose_name_plural': 'Factory compliances',
            },
        ),
    ]
