# Generated by Django 6.1 on 2026-08-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('doc_type', models.CharField(choices=[('buyer_agreement', 'Buyer Agreement'), ('compliance_manual', 'Compliance Manual'), ('quality_manual', 'Quality Manual'), ('packaging_guideline', 'Packaging Guideline'), ('rsl', 'RSL'), ('brand_guideline', 'Brand Guideline'), ('po', 'PO'), ('pi', 'PI'), ('lc', 'LC'), ('bl', 'Bill of Lading'), ('awb', 'Air Waybill'), ('commercial_invoice', 'Commercial Invoice'), ('packing_list', 'Packing List'), ('certificate_of_origin', 'Certificate of Origin'), ('inspection_certificate', 'Inspection Certificate'), ('test_report', 'Test Report'), ('other', 'Other')], max_length=40)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
