# Generated by Django 6.1 on 2026-08-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('fabric_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('trims_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cm_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('washing_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('freight_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
