# Generated by Django 6.1 on 2026-09-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fabric', 'Fabric'), ('trims', 'Trims'), ('labels_packing', 'Labels & Packing'), ('embellishment', 'Embellishment'), ('cm', 'CM'), ('washing', 'Washing'), ('test_cost', 'Test Cost'), ('commercial_charges', 'Commercial Charges'), ('profit_margin', 'Profit Margin')], max_length=20)),
                ('component_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('supplier_info', models.CharField(blank=True, max_length=150, verbose_name='Supplier Information')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('consumption', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('wastage_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Cost in US$')),
            ],
            options={
                'verbose_name': 'Costing Line',
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CostingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
