# Generated by Django 6.1 on 2026-09-11 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costingsheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costing_sheets', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='costingline',
            name='costing_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='costing.costingsheet'),
        ),
        migrations.AlterUniqueTogether(
            name='costingsheet',
            unique_together={('order_item', 'version')},
        ),
    ]
