# Generated by Django 6.1 on 2026-08-30 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_initial'),
        ('items', '0004_alter_finisheditemvariant_size'),
        ('orders', '0003_remove_order_our_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemBOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fabric', 'Fabric'), ('trims', 'Trims'), ('accessories', 'Accessories'), ('packaging', 'Packaging'), ('label', 'Label'), ('other', 'Other')], max_length=20)),
                ('consumption', models.DecimalField(decimal_places=4, help_text='Quantity of this material needed to make 1 finished unit', max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pcs'), ('yds', 'Yards'), ('mtr', 'Meter'), ('kg', 'Kg'), ('gm', 'Gram'), ('set', 'Set'), ('dozen', 'Dozen'), ('roll', 'Roll')], default='pcs', max_length=10)),
                ('wastage_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_bom_lines', to='items.item')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Order BOM Line',
                'ordering': ['category', 'item__description'],
            },
        ),
        migrations.CreateModel(
            name='StandardBOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fabric', 'Fabric'), ('trims', 'Trims'), ('accessories', 'Accessories'), ('packaging', 'Packaging'), ('label', 'Label'), ('other', 'Other')], max_length=20)),
                ('consumption', models.DecimalField(decimal_places=4, help_text='Quantity of this material needed to make 1 finished unit', max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pcs'), ('yds', 'Yards'), ('mtr', 'Meter'), ('kg', 'Kg'), ('gm', 'Gram'), ('set', 'Set'), ('dozen', 'Dozen'), ('roll', 'Roll')], default='pcs', max_length=10)),
                ('wastage_percent', models.DecimalField(decimal_places=2, default=0, help_text='Wastage / buffer %, e.g. 5 for 5%', max_digits=5)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('finished_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='items.finisheditem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_bom_lines', to='items.item')),
            ],
            options={
                'verbose_name': 'Standard BOM Line',
                'ordering': ['category', 'item__description'],
            },
        ),
    ]
