# Generated by Django 6.1 on 2026-09-11 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('website', models.URLField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('buyer_type', models.CharField(choices=[('local', 'Local'), ('international', 'International')], max_length=15)),
                ('category', models.CharField(choices=[('brand', 'Brand'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('incoterms', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('default_factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_buyers', to='factories.factory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BuyerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=80)),
                ('department', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('wechat', models.CharField(blank=True, max_length=30)),
                ('kakao', models.CharField(blank=True, max_length=30)),
                ('preferred_channel', models.CharField(blank=True, max_length=20)),
                ('alternate_contact', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='buyers.buyer')),
            ],
            options={
                'verbose_name_plural': 'Buyer contacts',
            },
        ),
        migrations.CreateModel(
            name='BuyerRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('packaging_requirement', models.TextField(blank=True)),
                ('label_requirement', models.TextField(blank=True)),
                ('poly_requirement', models.TextField(blank=True)),
                ('fabric_preference', models.TextField(blank=True)),
                ('special_requirement', models.TextField(blank=True)),
                ('aql', models.CharField(blank=True, max_length=20)),
                ('inspection_requirement', models.TextField(blank=True)),
                ('sample_requirement', models.CharField(blank=True, max_length=100)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='buyers.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerShipTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_to_addresses', to='buyers.buyer')),
            ],
            options={
                'verbose_name': 'Ship-to address',
                'verbose_name_plural': 'Ship-to addresses',
                'ordering': ['-is_default', 'label'],
            },
        ),
    ]
