# Generated by Django 6.1 on 2026-08-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('factories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplePO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=30, unique=True)),
                ('sample_type', models.CharField(choices=[('proto', 'Proto'), ('fit', 'Fit Sample'), ('pp', 'PP Sample')], max_length=10)),
                ('fabric_source', models.CharField(choices=[('buyer', 'Buyer-sourced'), ('factory', 'Factory-sourced')], max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('p_number', models.CharField(blank=True, max_length=30)),
                ('development_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('pending_submission', 'Pending Submission'), ('delivered', 'Delivered'), ('critical', 'Critical'), ('archived', 'Archived')], default='pending_submission', max_length=20)),
                ('requested_date', models.DateField()),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('md_approved', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_pos', to='buyers.buyer')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_pos', to='factories.factory')),
            ],
            options={
                'verbose_name': 'Sample PO',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='SampleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sample_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='samples.samplepo')),
            ],
        ),
    ]
