# Generated by Django 6.1 on 2026-08-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('required_ship_date', models.DateField(blank=True, editable=False, null=True)),
                ('planned_ship_date', models.DateField()),
                ('mode', models.CharField(choices=[('sea', 'Sea'), ('air', 'Air'), ('courier', 'Courier'), ('road', 'Road'), ('other', 'Other')], max_length=10)),
                ('status', models.CharField(choices=[('split', 'Split'), ('half', 'Half'), ('full', 'Full'), ('partial', 'Partial')], max_length=10)),
                ('vessel', models.CharField(blank=True, max_length=100)),
                ('container', models.CharField(blank=True, max_length=100)),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
            ],
            options={
                'ordering': ['-planned_ship_date'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('quantity_on_time', models.PositiveIntegerField(default=0)),
                ('quantity_outstanding', models.PositiveIntegerField(default=0)),
                ('document_status', models.CharField(default='pending', max_length=20)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='shipment.shipment')),
            ],
            options={
                'ordering': ['-followup_date'],
            },
        ),
    ]
