# Generated by Django 6.1 on 2026-09-11 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('customer_po_number', models.CharField(blank=True, max_length=50)),
                ('payment_method', models.CharField(choices=[('fob', 'FOB - Free On Board'), ('ex_works', 'Ex Works'), ('cpt', 'CPT - Carriage Paid To'), ('cif', 'CIF - Cost, Insurance & Freight'), ('fca', 'FCA - Free Carrier'), ('cfr', 'CFR - Cost & Freight'), ('dap', 'DAP - Delivered At Place'), ('ddp', 'DDP - Delivered Duty Paid')], max_length=15)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True, default='1. Quality should be as per buyer approval\n2. Color as per buyer approval')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='items.item')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
