# Generated by Django 6.1 on 2026-08-26 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factories', '0001_initial'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('customer_po_number', models.CharField(blank=True, max_length=50)),
                ('payment_method', models.CharField(choices=[('fob', 'FOB - Free On Board'), ('ex_works', 'Ex Works'), ('cpt', 'CPT - Carriage Paid To'), ('cif', 'CIF - Cost, Insurance & Freight'), ('fca', 'FCA - Free Carrier'), ('cfr', 'CFR - Cost & Freight'), ('dap', 'DAP - Delivered At Place'), ('ddp', 'DDP - Delivered Duty Paid')], max_length=15)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_destination', to='factories.factory', verbose_name='Destination')),
                ('to_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_to', to='factories.factory', verbose_name='To (Supplier)')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='items.item')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase_orders.purchaseorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
