# Generated by Django 6.1 on 2026-08-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='1. Quality should be as per buyer approval\n2. Color as per buyer approval'),
        ),
    ]
