# Generated by Django 6.1 on 2026-08-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_type', models.CharField(choices=[('sample', 'Sample'), ('bulk', 'Bulk')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('lc_status', models.CharField(blank=True, max_length=50)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('ready_quantity', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Follow-up entries',
                'ordering': ['-date'],
            },
        ),
    ]
